/* Offline machinery for the whole site. Generated by
   build/build_site.py; do not edit by hand, the next build overwrites it.
   Two caches with different lifetimes: CORE precaches the installable tools,
   and its versioned name retires it whenever a cached file changes. PAGES
   holds everything a reader has visited, plus the full offline copy if they
   asked for one. Its name is a digest of the contents of every file the
   offline copy lists, so a publish changes it; on activate the new worker
   carries every entry of the previous generation across before deleting
   it, so nothing a reader saved is lost. A saved full copy then refreshes
   itself: the manifest carries a digest per file, and only the files whose
   digest moved are fetched again. Caches named term-* belong to the /term/
   instrument's own worker, which manages its own versions; they are not
   this worker's to delete. */
const VERSION  = "b7a8ce856495";
const CORE     = "site-" + VERSION;
const PAGES    = "site-pages-735955f5af51";
const MANIFEST = "offline-manifest.json";
const FILES    = [
  "daily-learning-cockpit-192.png",
  "daily-learning-cockpit-512.png",
  "daily-learning-cockpit.html",
  "daily-learning-cockpit.webmanifest",
  "law-arena-192.png",
  "law-arena-512.png",
  "law-arena.html",
  "law-arena.webmanifest",
  "skill-forge-192.png",
  "skill-forge-512.png",
  "skill-forge.html",
  "skill-forge.webmanifest"
];
// The editor is never served from this cache: an administrative page read
// from a stale copy would show yesterday's list and publish over today's.
// It goes to the network every time, is stored by nothing here, and is
// dropped from any earlier generation that held it.
const NEVER_STORED = ["admin.html"];

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(CORE)
      // addAll is all-or-nothing, so one missing file would leave the tools
      // with no cache at all. Each file is added on its own and a failure is
      // survivable: the rest still work offline.
      .then(c => Promise.all(FILES.map(f => c.add(f).catch(() => null))))
      .then(() => self.skipWaiting())
  );
});

/* Carry the previous generation across. Every entry the reader held is
   copied into the new cache before the old one is deleted; a page copied
   this way is one publish old until it is visited (the fetch handler
   refreshes it then) or until the full copy syncs itself below. */
async function migrate() {
  const keys = await caches.keys();
  const old = keys.filter(k => k.indexOf("site-pages-") === 0 && k !== PAGES);
  if (!old.length) return false;
  const nc = await caches.open(PAGES);
  for (const k of old) {
    const oc = await caches.open(k);
    for (const req of await oc.keys()) {
      if (await nc.match(req)) continue;
      const res = await oc.match(req);
      if (res) await nc.put(req, res);
    }
    await caches.delete(k);
  }
  return true;
}

self.addEventListener("activate", e => {
  e.waitUntil((async () => {
    await migrate();
    const keys = await caches.keys();
    await Promise.all(keys
      .filter(k => k !== CORE && k !== PAGES && k.indexOf("term-") !== 0)
      .map(k => caches.delete(k)));
    await self.clients.claim();
    // a saved full copy refreshes itself against the new manifest
    const c = await caches.open(PAGES);
    for (const f of NEVER_STORED) await c.delete(f);
    if (await c.match(MANIFEST)) await sync(broadcast, false);
  })());
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  if (NEVER_STORED.indexOf(url.pathname.replace(/^\//, "")) >= 0) {
    e.respondWith(fetch(req).catch(() =>
      new Response("The editor is never served from the cache; it needs the network.",
        { status: 503, headers: { "content-type": "text/plain; charset=utf-8" } })));
    return;
  }

  // Cache first, refresh behind: a click on a saved page opens from disk
  // with no network wait at all, while the fetch that follows replaces the
  // stored copy so the next click is current. A page seen after a publish
  // is therefore at most one visit old, and never slow.
  e.respondWith(
    caches.match(req).then(hit => {
      const refresh = fetch(req)
        .then(res => {
          if (res && res.ok && res.type === "basic") {
            const copy = res.clone();
            caches.open(PAGES).then(c => c.put(req, copy)).catch(() => {});
          }
          return res;
        });
      if (hit) { refresh.catch(() => {}); return hit; }
      return refresh.catch(() =>
        caches.match(url.pathname.replace(/^\//, "") || "index.html")
          .then(h2 => h2 || caches.match("index.html")));
    })
  );
});

async function broadcast(m) {
  const cs = await self.clients.matchAll({ includeUncontrolled: true });
  cs.forEach(c => c.postMessage(m));
}

/* The full offline copy, saved or refreshed by the same routine: read the
   live manifest, compare each file's digest with the manifest last synced,
   fetch what is new or changed, drop what the site no longer lists, then
   store the manifest itself as the record of what is held. "force" fetches
   everything, which is what the colophon's button asks for. */
async function sync(tell, force) {
  let man;
  try {
    man = await (await fetch(MANIFEST, { cache: "no-cache" })).json();
  } catch (err) { tell({ type: "cache-all-done", ok: 0, failed: -1 }); return; }
  const c = await caches.open(PAGES);
  const heldRes = await c.match(MANIFEST);
  let held = null;
  try { held = heldRes ? await heldRes.json() : null; } catch (err) { held = null; }
  const was = (held && held.digests) || {};
  const now = man.digests || {};
  const files = man.files || [];
  const todo = [];
  for (const f of files) {
    if (force || !was[f] || was[f] !== now[f] || !(await c.match(f))) todo.push(f);
  }
  // files the site no longer lists leave the copy
  for (const req of await c.keys()) {
    const name = new URL(req.url).pathname.replace(/^\//, "");
    if (name && name !== MANIFEST && was[name] && !now[name]) await c.delete(req);
  }
  let ok = 0, failed = 0, i = 0;
  const pool = 6;
  async function worker() {
    while (i < todo.length) {
      const f = todo[i++];
      try {
        const res = await fetch(f, { cache: "no-cache" });
        if (res && res.ok) { await c.put(f, res); ok++; }
        else failed++;
      } catch (err) { failed++; }
      if ((ok + failed) % 5 === 0 || ok + failed === todo.length)
        tell({ type: "cache-all-progress", done: ok + failed, total: todo.length });
    }
  }
  await Promise.all(Array.from({ length: pool }, worker));
  if (!failed) {
    await c.put(MANIFEST, new Response(JSON.stringify(man),
      { headers: { "content-type": "application/json" } }));
  }
  tell({ type: "cache-all-done", ok, failed, total: todo.length, held: await count(c, files), of: files.length, version: man.version });
}

async function count(c, files) {
  let n = 0;
  for (const f of files) if (await c.match(f)) n++;
  return n;
}

/* What this phone holds, read from the cache rather than remembered: how
   many of the listed files are present, which manifest version they were
   synced against, and whether that is the live version when the network
   can say. */
async function status(tell) {
  const c = await caches.open(PAGES);
  const heldRes = await c.match(MANIFEST);
  let held = null;
  try { held = heldRes ? await heldRes.json() : null; } catch (err) { held = null; }
  let live = null;
  try { live = await (await fetch(MANIFEST, { cache: "no-cache" })).json(); } catch (err) { live = null; }
  const files = (held || live || {}).files || [];
  tell({ type: "status", held: await count(c, files), of: files.length,
         saved: !!held, version: held ? held.version : null,
         live: live ? live.version : null });
}

self.addEventListener("message", e => {
  const msg = e.data || {};
  const tell = m => { if (e.source) e.source.postMessage(m); };
  if (msg.type === "cache-all") {
    e.waitUntil(sync(tell, true));
  } else if (msg.type === "status") {
    e.waitUntil(status(tell));
  } else if (msg.type === "drop-all") {
    e.waitUntil(caches.delete(PAGES).then(() => tell({ type: "drop-all-done" })));
  }
});
